# Generated by Django 4.2.11 on 2024-07-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_categoryfollowers_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', through='api.PostCategories', to='api.category'),
        ),
    ]
