version: "3.8"
services:
    backend:
        image: rigomoreirar/code-connect-backend:latest
        ports:
            - "8000:8000"
        restart: unless-stopped
        volumes:
            - ./data:/data

    frontend:
        container_name: frontend
        image: rigomoreirar/code-connect-frontend:latest
        expose:
            - "3000"

    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./frontend/nginx.conf:/etc/nginx/nginx.conf
            - ./frontend/codeconnect.lat.crt:/etc/ssl/certs/codeconnect.lat.crt
            - ./frontend/codeconnect.lat.ca-bundle:/etc/ssl/certs/codeconnect.lat.ca-bundle
            - ./frontend/codeconnect.lat.p7b:/etc/ssl/private/codeconnect.lat.p7b
        depends_on:
            - frontend
