version: "3.8"
services:
    backend:
        image: rigomoreirar/code-connect-backend:2.001
        expose:
            - "8000"
        restart: unless-stopped
        volumes:
            - ./data:/data
        networks:
            - code-connect-network
        deploy:
            update_config:
                order: start-first
        env_file:
            - ./.env

    frontend:
        container_name: frontend
        image: rigomoreirar/code-connect-frontend:2.001
        expose:
            - "3000"
        networks:
            - code-connect-network
        deploy:
            update_config:
                order: start-first

    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./frontend/nginx.conf:/etc/nginx/nginx.conf
            - ./codeconnect.crt:/etc/ssl/codeconnect.crt
            - ./codeconnect.key:/etc/ssl/codeconnect.key
        depends_on:
            - frontend
        networks:
            - code-connect-network

networks:
    code-connect-network:
