version: "3.8"
services:
    backend:
        image: rigomoreirar/code-connect-backend:3.74
        environment:
            SECRET_KEY: ${SECRET_KEY}
        expose:
            - "8000"
        restart: unless-stopped
        volumes:
            - ./data:/data
            - ./backend/build:/code/frontend/build # Ensure build directory is correctly mounted
        networks:
            - code-connect-network

    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./backend/build:/code/frontend/build # Ensure build directory is correctly mounted
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./codeconnect.crt:/etc/ssl/codeconnect.crt
            - ./codeconnect.key:/etc/ssl/codeconnect.key
        depends_on:
            - backend
        networks:
            - code-connect-network

networks:
    code-connect-network:
