version: "3.8"
services:
    backend:
        image: rigomoreirar/code-connect-backend:latest
        ports:
            - "8000:8000"
        restart: unless-stopped
        volumes:
            - ./data:/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 100s # Add an initial delay before health checks start
        networks:
            - mynetwork

    frontend:
        image: rigomoreirar/code-connect-frontend:latest
        ports:
            - "80:80"
        restart: unless-stopped
        depends_on:
            - backend
        networks:
            - mynetwork

networks:
    mynetwork:
