version: "3.8"
services:
    backend:
        image: rigomoreirar/code-connect-backend:4.2.1
        environment:
            SECRET_KEY: ${SECRET_KEY}
        expose:
            - "8000"
        restart: unless-stopped
        volumes:
            - ./data:/data
        networks:
            - code-connect-network
    sse-backend:
        image: rigomoreirar/code-connect-backend:4.2.1
        environment:
            SECRET_KEY: ${SECRET_KEY}
        expose:
            - "8000"
        restart: unless-stopped
        volumes:
            - ./data:/data
        networks:
            - code-connect-network

    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./codeconnect.crt:/etc/ssl/codeconnect.crt
            - ./codeconnect.key:/etc/ssl/codeconnect.key
            - ./backend/frontend/build/:/code/frontend/build/
            - ./backend/assets/profile-pictures:/code/assets/profile-pictures
        depends_on:
            - backend
            - sse-backend
        networks:
            - code-connect-network

networks:
    code-connect-network:
