version: "3.8"
services:
    backend:
        image: rigomoreirar/code-connect-backend:latest
        ports:
            - "8000:8000"
        restart: unless-stopped
        volumes:
            - ./data:/data

    frontend:
        container_name: frontend
        image: rigomoreirar/code-connect-frontend:latest
        expose:
            - "3000"

    nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./frontend/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        depends_on:
            - frontend
            - certbot

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"
