# name: Build and Deploy to Azure Container Instances

# on:
#   workflow_dispatch:

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Build and push Docker backend image
#         uses: docker/build-push-action@v2
#         with:
#           context: ./backend
#           push: true
#           tags: rigomoreirar/code-connect-backend:latest

#       - name: Build and push Docker frontend image
#         uses: docker/build-push-action@v2
#         with:
#           context: ./frontend
#           push: true
#           tags: rigomoreirar/code-connect-frontend:latest

#       - name: Log in to Azure
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#         env:
#           AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
#           AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
#           AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

#       - name: Create container group definition
#         run: |
#           cat <<EOF > container-group.yaml
#           {
#             "apiVersion": "2021-03-01",
#             "location": "eastus",
#             "name": "app-instances",
#             "properties": {
#               "containers": [
#                 {
#                   "name": "backend",
#                   "properties": {
#                     "image": "rigomoreirar/code-connect-backend:latest",
#                     "ports": [
#                       {
#                         "port": 8000
#                       }
#                     ],
#                     "resources": {
#                       "requests": {
#                         "cpu": 1,
#                         "memoryInGB": 1.5
#                       }
#                     }
#                   }
#                 },
#                 {
#                   "name": "frontend",
#                   "properties": {
#                     "image": "rigomoreirar/code-connect-frontend:latest",
#                     "ports": [
#                       {
#                         "port": 5000
#                       }
#                     ],
#                     "resources": {
#                       "requests": {
#                         "cpu": 1,
#                         "memoryInGB": 1
#                       }
#                     }
#                   }
#                 }
#               ],
#               "osType": "Linux",
#               "ipAddress": {
#                 "type": "Public",
#                 "ports": [
#                   {
#                     "protocol": "tcp",
#                     "port": 8000
#                   },
#                   {
#                     "protocol": "tcp",
#                     "port": 5000
#                   }
#                 ]
#               }
#             }
#           }
#           EOF

#       - name: Deploy to Azure Container Instances
#         run: |
#           az container create --resource-group instances --file container-group.yaml
