name: Push Docker image to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: rigomoreirar/code-connect-backend:latest

      - name: Build and push Docker frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: rigomoreirar/code-connect-frontend:latest